package com.example.parser

import androidx.compose.ui.graphics.Color
import com.example.model.SubtitleCue
import com.example.model.SubtitleHorizontalAlign
import com.example.model.SubtitleStyle
import com.example.model.SubtitleVerticalAlign
import java.util.Locale
import kotlin.math.roundToInt

object AssGenerator {

    /**
     * Formats milliseconds to ASS timestamp: H:MM:SS.cs (centiseconds)
     */
    fun formatAssTimestamp(ms: Long): String {
        val nonNegativeMs = ms.coerceAtLeast(0L)
        val hours = nonNegativeMs / 3600000L
        val minutes = (nonNegativeMs % 3600000L) / 60000L
        val seconds = (nonNegativeMs % 60000L) / 1000L
        val centiseconds = (nonNegativeMs % 1000L) / 10L
        return String.format(Locale.US, "%d:%02d:%02d.%02d", hours, minutes, seconds, centiseconds)
    }

    /**
     * Converts Compose Color to ASS color format: &HAABBGGRR
     * Note: In ASS, 00 is fully opaque, FF is fully transparent
     */
    fun colorToAssHex(color: Color): String {
        val alphaInt = (color.alpha * 255f).roundToInt().coerceIn(0, 255)
        val assAlpha = 255 - alphaInt // Invert alpha for ASS standard
        val red = (color.red * 255f).roundToInt().coerceIn(0, 255)
        val green = (color.green * 255f).roundToInt().coerceIn(0, 255)
        val blue = (color.blue * 255f).roundToInt().coerceIn(0, 255)
        return String.format(Locale.US, "&H%02X%02X%02X%02X", assAlpha, blue, green, red)
    }

    /**
     * Converts Compose Color to inline ASS override color tag value: &HBBGGRR&
     */
    fun colorToInlineAssHex(color: Color): String {
        val red = (color.red * 255f).roundToInt().coerceIn(0, 255)
        val green = (color.green * 255f).roundToInt().coerceIn(0, 255)
        val blue = (color.blue * 255f).roundToInt().coerceIn(0, 255)
        return String.format(Locale.US, "&H%02X%02X%02X&", blue, green, red)
    }

    /**
     * Maps vertical & horizontal alignments to ASS alignment number (1-9 numpad layout)
     */
    fun getAssAlignment(vertical: SubtitleVerticalAlign, horizontal: SubtitleHorizontalAlign): Int {
        return when (vertical) {
            SubtitleVerticalAlign.TOP -> when (horizontal) {
                SubtitleHorizontalAlign.LEFT -> 7
                SubtitleHorizontalAlign.CENTER -> 8
                SubtitleHorizontalAlign.RIGHT -> 9
            }
            SubtitleVerticalAlign.MIDDLE -> when (horizontal) {
                SubtitleHorizontalAlign.LEFT -> 4
                SubtitleHorizontalAlign.CENTER -> 5
                SubtitleHorizontalAlign.RIGHT -> 6
            }
            SubtitleVerticalAlign.BOTTOM -> when (horizontal) {
                SubtitleHorizontalAlign.LEFT -> 1
                SubtitleHorizontalAlign.CENTER -> 2
                SubtitleHorizontalAlign.RIGHT -> 3
            }
        }
    }

    /**
     * Generates a complete, standard .ASS (Advanced SubStation Alpha v4.00+) script
     * seamlessly incorporating font styles, positions, and dialogue cues.
     */
    fun generateAss(
        title: String,
        subtitles: List<SubtitleCue>,
        style: SubtitleStyle,
        applyTimeOffset: Boolean = false,
        videoWidth: Int = 1920,
        videoHeight: Int = 1080,
        additionalStyles: List<String> = emptyList()
    ): String {
        val sb = StringBuilder()

        val playResX = if (videoWidth > 0) videoWidth else 1920
        val playResY = if (videoHeight > 0) videoHeight else 1080

        // [Script Info]
        sb.appendLine("[Script Info]")
        sb.appendLine("; Script generated by remsubs playground (AxiSub)")
        sb.appendLine("; Synchronized & Styled in Real-time")
        sb.appendLine("Title: $title")
        sb.appendLine("ScriptType: v4.00+")
        sb.appendLine("WrapStyle: 0")
        sb.appendLine("ScaledBorderAndShadow: yes")
        sb.appendLine("PlayResX: $playResX")
        sb.appendLine("PlayResY: $playResY")
        sb.appendLine()

        // [V4+ Styles]
        sb.appendLine("[V4+ Styles]")
        sb.appendLine("Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding")

        val fontName = style.fontName.ifBlank { "Arial" }
        val fontSize = style.fontSizeSp.toInt().coerceAtLeast(10)
        val primaryColour = colorToAssHex(style.textColor)
        val secondaryColour = "&H000000FF"
        val outlineColour = colorToAssHex(style.outlineColor)
        val backColour = colorToAssHex(style.backgroundColor)
        val bold = if (style.isBold) -1 else 0
        val italic = if (style.isItalic) -1 else 0
        val underline = if (style.isUnderline) -1 else 0
        val borderStyle = if (style.hasBackgroundBox) 3 else 1
        val outlineWidth = if (style.hasOutline) style.outlineWidth.toInt().coerceAtLeast(1) else 0
        val shadowDepth = if (style.hasOutline) 1 else 0
        val alignment = getAssAlignment(style.verticalAlign, style.horizontalAlign)
        val marginL = style.horizontalPaddingDp.toInt().coerceAtLeast(10)
        val marginR = style.horizontalPaddingDp.toInt().coerceAtLeast(10)
        val marginV = style.verticalOffsetDp.toInt().coerceAtLeast(10)

        sb.appendLine("Style: Default,$fontName,$fontSize,$primaryColour,$secondaryColour,$outlineColour,$backColour,$bold,$italic,$underline,0,100,100,0,0,$borderStyle,$outlineWidth,$shadowDepth,$alignment,$marginL,$marginR,$marginV,1")

        // Include any additional styles defined in original ASS file or cues
        val declaredStyleNames = mutableSetOf("Default", "default")
        for (extraStyleLine in additionalStyles) {
            val trimmed = extraStyleLine.trim()
            if (trimmed.startsWith("Style:", ignoreCase = true)) {
                val parts = trimmed.substring(6).trim().split(",")
                if (parts.isNotEmpty()) {
                    val sName = parts[0].trim()
                    if (sName.isNotEmpty() && !declaredStyleNames.contains(sName.lowercase())) {
                        sb.appendLine(trimmed)
                        declaredStyleNames.add(sName.lowercase())
                    }
                }
            }
        }

        // For any cue with a distinct styleName not yet declared, create a fallback style
        for (cue in subtitles) {
            val sName = cue.styleName.trim()
            if (sName.isNotBlank() && !declaredStyleNames.contains(sName.lowercase())) {
                sb.appendLine("Style: $sName,$fontName,$fontSize,$primaryColour,$secondaryColour,$outlineColour,$backColour,$bold,$italic,$underline,0,100,100,0,0,$borderStyle,$outlineWidth,$shadowDepth,$alignment,$marginL,$marginR,$marginV,1")
                declaredStyleNames.add(sName.lowercase())
            }
        }

        sb.appendLine()

        // [Events]
        sb.appendLine("[Events]")
        sb.appendLine("Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text")

        val timeOffset = if (applyTimeOffset) style.timeOffsetMs else 0L

        for (cue in subtitles.sortedBy { it.startTimeMs }) {
            val startMs = (cue.startTimeMs + timeOffset).coerceAtLeast(0L)
            val endMs = (cue.endTimeMs + timeOffset).coerceAtLeast(startMs)
            val startStr = formatAssTimestamp(startMs)
            val endStr = formatAssTimestamp(endMs)

            // Format dialogue text with custom per-cue overrides if set
            val formattedText = formatCueTextForAss(cue)
            val layer = cue.layer
            val styleName = if (cue.styleName.isNotBlank()) cue.styleName else "Default"
            val actor = cue.actor
            val marginVVal = if (cue.marginV > 0) cue.marginV else 0

            sb.appendLine("Dialogue: $layer,$startStr,$endStr,$styleName,$actor,0,0,$marginVVal,,$formattedText")
        }

        return sb.toString()
    }

    private fun formatCueTextForAss(cue: SubtitleCue): String {
        val baseText = (if (cue.rawText.isNotBlank()) cue.rawText else cue.cleanText)
            .replace("\r\n", "\\N")
            .replace("\n", "\\N")

        if (!cue.customPositionEnabled) {
            return baseText
        }

        // Build ASS override tags for this specific cue
        val tags = StringBuilder()
        val customAlign = getAssAlignment(cue.customVerticalAlign, cue.customHorizontalAlign)
        tags.append("\\an$customAlign")

        cue.customFontSizeSp?.let { size ->
            tags.append("\\fs${size.toInt()}")
        }

        cue.customTextColorArgb?.let { argb ->
            val red = (argb shr 16 and 0xFF)
            val green = (argb shr 8 and 0xFF)
            val blue = (argb and 0xFF)
            val hex = String.format(Locale.US, "&H%02X%02X%02X&", blue, green, red)
            tags.append("\\c$hex")
        }

        cue.customOutlineColorArgb?.let { argb ->
            val red = (argb shr 16 and 0xFF)
            val green = (argb shr 8 and 0xFF)
            val blue = (argb and 0xFF)
            val hex = String.format(Locale.US, "&H%02X%02X%02X&", blue, green, red)
            tags.append("\\3c$hex")
        }

        cue.customIsItalic?.let {
            tags.append(if (it) "\\i1" else "\\i0")
        }

        cue.customIsBold?.let {
            tags.append(if (it) "\\b1" else "\\b0")
        }

        cue.customIsUnderline?.let {
            tags.append(if (it) "\\u1" else "\\u0")
        }

        return "{$tags}$baseText"
    }
}
